### ISSUE TITLE
Forcing the parallels code chunks to be at the same size

### ISSUE THREAD

**Issue by hugosantanna** [grantmcdermott/two-col-test#4]
tbh, I believe it must be a trivial issue.

When trying to deal with different code length in the page, it breaks the first paragraph after the columns display.

<img width="1033" alt="Screen Shot 2020-01-06 at 10 51 11" src="https://user-images.githubusercontent.com/47804685/71821997-7543bd00-3072-11ea-9823-5f22d6bfcaa6.png">

**Comment by grantmcdermott** [comment]
Hi @hsantanna88 

Sorry for the slow reply. I've updated my repo to reflect new best practices for specifying multicolumn environments (basically using Pandoc's fenced_div approach). 

I don't think this will size the code blocks to be the same. But it should at least fill with whitespace on the shorter column so that any subsequent (full width) text is correctly aligned.

Closing, but feel free to comment and let me know if this solves the problem for you.
